package com.thaistads.sispecort.enums;

public enum Doencas {
	ANAPLASMOSE,
	BABESIOSE,
	BOTULISMO,
	BRUCELOSE,
	CAMPILOBACTERIOSE,
	CARBUNCULOHEMATICO,
	CARBUNCULOSINTOMATICO,
	CERATOCONJUTIVITE,
	COLIBACILOSE,
	CORONAVIRUS,
	BVDMD,
	ENTEROTOXEMIA,
	FEBREAFTOSA,
	GANGRENAGASOSA,
	HEMOGLOBINURIABACILAR,
	LEPTOSPIROSE,
	PASTEURELOSE,
	PARAINFLUENZABOVINATIPO3,
	RAIVA,
	RINOTRAQUEITEINFECCIOSABOVINA,
	ROTAVIRUS,
	SALMONELOSE,
	TETANO,
	VIRUSRESPIRATORIOSINCICIALDOSBOVINOS;
	

}
