package com.thaistads.sispecort.enums;

public enum TipoDeParceiros {
	CRIADOR,
	RECRIADOR,
	TERMINADOR,
	FRIGORIFICO, 
	MEDICOVETERINARIO,
	ENGENHEIROAGRONOMO,
	CONSULTOR,
	CONTADOR,
	FRETEIRO,
	CASAAGROPECUARIA,
	ZOOTECNISTA,
	TECNICO,
	LEILAO,
	ALUGUEL,
	FORNECEDOR,
	PRESTADORDESERVICOS,
	OUTROS;
}
